apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-store-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: feature-store
  template:
    metadata:
      labels:
        app: feature-store
    spec:
      containers:
      - name: feature-store
        image: your-docker-image
        ports:
        - containerPort: 8000
